name: auto-update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_UPDATE_TOKEN }}

      - name: Get latest version
        id: latest-version
        run: |
          MORELLOIE_FILENAME="$(curl -fsSL "https://developer.arm.com/downloads/-/morello-instruction-emulator" | grep -o -e 'Download morelloie-.*.sh' | cut -d ' ' -f 2 | sort -nr | head -n1)"
          echo "Using morelloie filename: ${MORELLOIE_FILENAME}"
          NO_PREFIX="${MORELLOIE_FILENAME#morelloie-}"
          export MORELLOIE_VERSION="${NO_PREFIX%%.tgz.sh}"

          MORELLO_LLVM_FILENAME="$(curl -fsSL "https://git.morello-project.org/morello/llvm-project-releases/-/raw/main/README.md?ref_type=heads" | grep -o -e 'morello-llvm-linux-aarch64-[0-9.]*.tar.gz')"
          echo "Using morello LLVM filename: ${MORELLO_LLVM_FILENAME}"
          NO_PREFIX="${MORELLO_LLVM_FILENAME#morello-llvm-linux-aarch64-}"
          export MORELLO_LLVM_VERSION="${NO_PREFIX%%.tar.gz}"

          rm -rf musl-libc
          git clone --depth=1 https://git.morello-project.org/morello/musl-libc.git
          cd musl-libc
          MUSL_VERSION="$(git rev-parse --short HEAD)"

          echo "Latest morelloie version: ${MORELLOIE_VERSION}"
          echo "Latest morello LLVM version: ${MORELLO_LLVM_VERSION}"
          echo "Latest musl version: ${MUSL_VERSION}"

          echo "morelloie_version=${MORELLOIE_VERSION}" >> $GITHUB_OUTPUT
          echo "morello_llvm_version=${MORELLO_LLVM_VERSION}" >> $GITHUB_OUTPUT
          echo "musl_version=${MUSL_VERSION}" >> $GITHUB_OUTPUT

          TAG_NAME="v${MORELLOIE_VERSION}_${MORELLO_LLVM_VERSION}_${MUSL_VERSION}"
          echo "tag=${TAG_NAME}" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.5.0
        id: check-tag
        with: 
          tag: ${{ steps.latest-version.outputs.tag }}
          repo: 'cocoa-xu/aarch64c-linux-sysroot'
      
      - name: Update if tag not exists
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.latest-version.outputs.tag }}
          git push origin ${{ steps.latest-version.outputs.tag }}
