name: auto-update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_UPDATE_TOKEN }}

      - name: Get latest version
        id: latest-version
        run: |
          MORELLOIE_FILENAME="$(curl -fsSL "https://developer.arm.com/downloads/-/morello-instruction-emulator" | grep -o -e 'Download morelloie-.*.sh' | cut -d ' ' -f 2 | sort -nr | head -n1)"
          export MORELLOIE_VERSION="${${MORELLOIE_FILENAME#morelloie-}%.tgz.sh}"
          MORELLO_LLVM_FILENAME="$(curl -fsSL https://git.morello-project.org/morello/llvm-project-releases/-/raw/main/README.md\?ref_type\=heads | grep -o -e 'morello-llvm-linux-[0-9.]*.tar.gz')"
          export MORELLO_LLVM_VERSION="${${MORELLO_LLVM_FILENAME#morello-llvm-linux-}%.tar.gz}"

          echo "Latest morelloie version: ${MORELLOIE_VERSION}"
          echo "Latest morelloie LLVM version: ${MORELLO_LLVM_VERSION}"

          echo "morelloie_version=${MORELLOIE_VERSION}" >> $GITHUB_OUTPUT
          echo "morello_llvm_version=${MORELLO_LLVM_VERSION}" >> $GITHUB_OUTPUT

          TAG_NAME="v${MORELLOIE_VERSION}+${MORELLO_LLVM_VERSION}"
          echo "tag=${TAG_NAME}" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.5.0
        id: check-tag
        with: 
          tag: ${{ steps.latest-version.outputs.tag }}
          repo: 'cocoa-xu/aarch64c-linux-sysroot'
      
      - name: Update if tag not exists
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.latest-version.outputs.tag }}
          git push origin ${{ steps.latest-version.outputs.tag }}
