name: build-sysroot

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - '**/*.md'
      - 'LICENSE*'
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '**/*.md'
      - 'LICENSE*'
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    if: "!contains(github.event.pull_request.labels.*.name, 'skip ci')"
    runs-on: self-hosted
    env:
      MORELLOIE_DOWNLOAD_URL: "https://developer.arm.com/-/media/Arm%20Developer%20Community/Downloads/Morello/Development%20Tools/Morello%20Instruction%20Emulator"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_UPDATE_TOKEN }}

      - name: Install system dependencies
        run: |
          sudo apt update -q=2
          sudo apt install -q=2 --yes --no-install-recommends --no-install-suggests curl git make

      - name: Parse versions
        id: parse-versions
        run: |
          case "${{ github.ref }}" in
            refs/tags/*)
              VERSIONS="${REF#v}"
              export MORELLOIE_VERSION="$(cho $VERSIONS | cut -d+ -f 1)"
              export MORELLO_LLVM_VERSION="$(echo $VERSIONS | cut -d+ -f 2)"
              export MUSL_VERSION="$(echo $VERSIONS | cut -d+ -f 3)"
              ;;
            *)
              MORELLOIE_FILENAME="$(curl -fsSL "https://developer.arm.com/downloads/-/morello-instruction-emulator" | grep -o -e 'Download morelloie-.*.sh' | cut -d ' ' -f 2 | sort -nr | head -n1)"
              echo "Using morelloie filename: ${MORELLOIE_FILENAME}"
              NO_PREFIX="${MORELLOIE_FILENAME#morelloie-}"
              export MORELLOIE_VERSION="${NO_PREFIX%%.tgz.sh}"

              MORELLO_LLVM_FILENAME="$(curl -fsSL "https://git.morello-project.org/morello/llvm-project-releases/-/raw/main/README.md?ref_type=heads" | grep -o -e 'morello-llvm-linux-[0-9.]*.tar.gz')"
              echo "Using morello LLVM filename: ${MORELLO_LLVM_FILENAME}"
              NO_PREFIX="${MORELLO_LLVM_FILENAME#morello-llvm-linux-}"
              export MORELLO_LLVM_VERSION="${NO_PREFIX%%.tar.gz}"

              export ROOT_DIR="$(pwd)"
              export MUSL_SOURCES=${HOME}/musl
              rm -rf ${MUSL_SOURCES}
              mkdir -p ${MUSL_SOURCES}
              git clone --depth=1 https://git.morello-project.org/morello/musl-libc.git "${MUSL_SOURCES}"
              cd "${MUSL_SOURCES}"
              export MUSL_VERSION="$(git rev-parse --short HEAD)"
              if [ ! -d "${HOME}/musl-${MUSL_VERSION}" ]; then
                mv "${MUSL_SOURCES}" "${MUSL_SOURCES}-${MUSL_VERSION}"
              fi
              ;;
          esac

          echo "Using morelloie version: ${MORELLOIE_VERSION}"
          echo "Using morello LLVM version: ${MORELLO_LLVM_VERSION}"
          echo "Using musl version: ${MUSL_VERSION}"

          echo "morelloie_version=${MORELLOIE_VERSION}" >> $GITHUB_OUTPUT
          echo "morello_llvm_version=${MORELLO_LLVM_VERSION}" >> $GITHUB_OUTPUT
          echo "musl_version=${MUSL_VERSION}" >> $GITHUB_OUTPUT

      - name: Cache Morello IE
        id: cache-morelloie
        uses: actions/cache@v3
        with:
          key: morelloie-${{ steps.parse-versions.outputs.morelloie_version }}
          path: |
            ./morelloie-${{ steps.parse-versions.outputs.morelloie_version }}.tgz.sh

      - name: Download Morello IE
        if: steps.cache-morelloie.outputs.cache-hit != 'true'
        run: |
          curl -fSL "${MORELLOIE_DOWNLOAD_URL}/morelloie-${{ steps.parse-versions.outputs.morelloie_version }}.tgz.sh" -o "morelloie-${{ steps.parse-versions.outputs.morelloie_version }}.tgz.sh"

      - name: Install Morello IE
        run: |
          export MORELLOIE_PREFIX=${HOME}/morelloie
          export MORELLOIE=${MORELLOIE_PREFIX}/bin/morelloie

          rm -rf ${HOME}/morelloie-* ${MORELLOIE_PREFIX}
          bash "morelloie-${{ steps.parse-versions.outputs.morelloie_version }}.tgz.sh" --i-agree-to-the-contained-eula --prefix=${MORELLOIE_PREFIX}

      - name: Cache Morello LLVM
        id: cache-morello-llvm
        uses: actions/cache@v3
        with:
          key: morello-llvm-${{ steps.parse-versions.outputs.morello_llvm_version }}
          path: |
            ./morello-llvm-linux-${{ steps.parse-versions.outputs.morello_llvm_version }}.tar.gz

      - name: Download Morello LLVM
        if: steps.cache-morello-llvm.outputs.cache-hit != 'true'
        run: |
          export MORELLO_LLVM_VERSION="${{ steps.parse-versions.outputs.morello_llvm_version }}"
          curl -fSL "https://git.morello-project.org/morello/llvm-project-releases/-/archive/morello/linux-release-${MORELLO_LLVM_VERSION}/llvm-project-releases-morello-linux-release-${MORELLO_LLVM_VERSION}.tar.gz" -o "morello-llvm-linux-${MORELLO_LLVM_VERSION}.tar.gz"

      - name: Install Morello LLVM
        run: |
          export LLVM_PREFIX=${HOME}/llvm
          rm -rf ${LLVM_PREFIX}
          mkdir -p ${LLVM_PREFIX}
          tar -xf "morello-llvm-linux-${{ steps.parse-versions.outputs.morello_llvm_version }}.tar.gz" -C ${LLVM_PREFIX} --strip-components=1

      - name: Checkout musl source code if not exists
        run: |
          export MUSL_SOURCES="${HOME}/musl-${{ steps.parse-versions.outputs.musl_version }}"
          if [ ! -d "${MUSL_SOURCES}" ]; then
            git clone --depth=1 https://git.morello-project.org/morello/musl-libc.git "${MUSL_SOURCES}"
            cd "${MUSL_SOURCES}"
            git checkout "${{ steps.parse-versions.outputs.musl_version }}"
          fi

      - name: Build Musl Sysroot for Purecap
        run: |
          export MUSL_PREFIX_PURECAP=${HOME}/musl-sysroot-purecap
          export MUSL_SOURCES="${HOME}/musl-${{ steps.parse-versions.outputs.musl_version }}"
          export LLVM_PREFIX=${HOME}/llvm
          pushd ${MUSL_SOURCES}
          make distclean
          CC=${LLVM_PREFIX}/bin/clang ./configure --prefix=${MUSL_PREFIX_PURECAP} --target=aarch64-linux-musl_purecap
          make -j`nproc`
          make install
          popd

      - name: Build Musl Sysroot for Hybrid
        run: |
          export MUSL_PREFIX_HYBRID=${HOME}/musl-sysroot-hybrid
          export MUSL_SOURCES="${HOME}/musl-${{ steps.parse-versions.outputs.musl_version }}"
          export LLVM_PREFIX=${HOME}/llvm
          pushd ${MUSL_SOURCES}
          make distclean
          CC=${LLVM_PREFIX}/bin/clang ./configure --prefix=${MUSL_PREFIX_HYBRID} --disable-morello --target=aarch64-linux-gnu
          make -j`nproc`
          make install
          popd

      - name: Create tarball
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd ${HOME}/musl-sysroot-purecap
          tar -czf /tmp/musl-sysroot-purecap.tar.gz .
          cd ${HOME}/musl-sysroot-hybrid
          tar -czf /tmp/musl-sysroot-hybrid.tar.gz .

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /tmp/musl-sysroot-*.tar.gz
